In [2]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

1.13.1
True


In [10]:
tensor_A = torch.rand(7,7)
tensor_B = torch.rand(1,7)

In [11]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[1.7197],
        [3.1125],
        [2.0645],
        [3.1271],
        [2.3144],
        [2.3593],
        [2.0623]])

In [14]:
torch.manual_seed(seed=0)
random_tensor_A = torch.rand(3, 4)

torch.random.manual_seed(seed=0)
random_tensor_B = torch.rand(3, 4)



In [15]:
random_tensor_A, random_tensor_B

(tensor([[0.4963, 0.7682, 0.0885, 0.1320],
         [0.3074, 0.6341, 0.4901, 0.8964],
         [0.4556, 0.6323, 0.3489, 0.4017]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320],
         [0.3074, 0.6341, 0.4901, 0.8964],
         [0.4556, 0.6323, 0.3489, 0.4017]]))

In [16]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [21]:
torch.cuda.manual_seed(seed=1234)
random_tensor_C = torch.randn(2,3).to(device)

torch.cuda.manual_seed(seed=1234)
random_tensor_D = torch.randn(2,3).to(device)

random_tensor_C, random_tensor_D

(tensor([[ 0.5186, -1.3125,  0.1920],
         [ 0.5428, -2.2188,  0.2590]], device='cuda:0'),
 tensor([[-1.0297, -0.5008,  0.2734],
         [-0.9181, -0.0404,  0.2881]], device='cuda:0'))

In [25]:
out = torch.matmul(random_tensor_C, random_tensor_D.T)

print(out)

tensor([[ 0.1757, -0.3678],
        [ 0.6230, -0.3340]], device='cuda:0')


In [26]:
print(torch.max(out))
print(torch.min(out))
print(torch.argmax(out))
print(torch.argmin(out))

tensor(0.6230, device='cuda:0')
tensor(-0.3678, device='cuda:0')
tensor(2, device='cuda:0')
tensor(1, device='cuda:0')


In [28]:
tensor_multi = torch.rand(1,1,1,10)
print(tensor_multi, tensor_multi.shape)

tensor([[[[0.0051, 0.1757, 0.7497, 0.6047, 0.1100, 0.2121, 0.9704, 0.8369,
           0.2820, 0.3742]]]]) torch.Size([1, 1, 1, 10])


In [30]:
tensor_E = torch.squeeze(tensor_multi)
tensor_E, tensor_E.shape

(tensor([0.0051, 0.1757, 0.7497, 0.6047, 0.1100, 0.2121, 0.9704, 0.8369, 0.2820,
         0.3742]),
 torch.Size([10]))